import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field, field_validator

from app.models.enums import EventSource, EventType
from app.utils.time import as_utc


class EventCreate(BaseModel):
    """Investor-created timeline entry. Allowed types: NOTE_ADDED, FOLLOW_UP_SENT.
    Stage changes go through PATCH /grievances/{id}; warnings are generated by the workflow engine."""

    event_type: EventType = EventType.NOTE_ADDED
    description: str = Field(min_length=1, max_length=2000)
    event_time: datetime | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("event_time")
    @classmethod
    def _tz(cls, v):
        if v is not None and v.tzinfo is None:
            return v.replace(tzinfo=timezone.utc)
        return v


class EventOut(BaseModel):
    id: uuid.UUID
    grievance_id: uuid.UUID
    event_type: EventType
    event_time: datetime
    source: EventSource
    description: str
    metadata: dict[str, Any] = Field(default_factory=dict)


def event_out(e) -> EventOut:
    return EventOut(
        id=e.id,
        grievance_id=e.grievance_id,
        event_type=e.event_type,
        event_time=as_utc(e.event_time),  # normalise naive (SQLite) and aware (Postgres) to UTC
        source=e.source,
        description=e.description or "",
        metadata=e.metadata_json or {},
    )
