import uuid

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.ai.summarizer import get_explanation_for_grievance
from app.api.deps import get_current_user
from app.db.session import get_db
from app.models.user import User
from app.schemas.common import ERROR_RESPONSES, ApiResponse, ok
from app.schemas.grievance import ExplanationOut
from app.services import grievance_service

router = APIRouter(prefix="/grievances", tags=["AI"])


@router.get(
    "/{grievance_id}/explanation",
    response_model=ApiResponse[ExplanationOut],
    summary="Plain-language explanation",
    description="Grounded AI summary generated by FlowGuard summarizer using real grievance details, timeline events, documents, and workflow status.",
    responses={401: ERROR_RESPONSES[401], 404: ERROR_RESPONSES[404]},
)
def explanation(grievance_id: str, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    g = grievance_service.get_owned_grievance(db, grievance_id, user)
    return ok(get_explanation_for_grievance(db, g))
