import {Grievance,GEvent,Doc,NextAction,Explanation,Summary,Notif,Me} from "@/types";
export const mockMe:Me={name:"Demo Investor",email:"demo@flowguard.app"};
export const mockG:Grievance={id:"demo-1",complaint_id:"CMP-2026-DEMO-001",entity_name:"Demo Brokerage Pvt Ltd",issue_type:"Transaction related grievance",issue_description:"Demo transaction grievance",submission_date:"2026-09-20T10:00:00Z",current_stage:"AWAITING_RESPONSE",status_updated_at:"2026-09-21T08:00:00Z",created_at:"2026-09-20T10:00:00Z",updated_at:"2026-09-21T08:00:00Z",
warnings:[{type:"POTENTIAL_DELAY",severity:"WARNING",rule_id:"DEMO_RULE_001",triggered_at:"2026-09-27T08:00:00Z",based_on_event:"e2",reason:"No response event has been recorded since the grievance entered AWAITING_RESPONSE. The monitoring window used here is demo configuration."}]};
const ev=(i:number,t:string,time:string,s:GEvent["source"],d:string):GEvent=>({id:"e"+i,grievance_id:"demo-1",event_type:t,event_time:time,source:s,description:d,metadata:{}});
export const mockE:GEvent[]=[ev(0,"FILED","2026-09-20T10:00:00Z","USER","Complaint filed."),ev(1,"ACKNOWLEDGED","2026-09-20T12:00:00Z","USER","Acknowledgement received."),ev(2,"AWAITING_RESPONSE","2026-09-21T08:00:00Z","SYSTEM","Status changed to Awaiting Response."),ev(3,"POTENTIAL_DELAY","2026-09-27T08:00:00Z","SYSTEM","FlowGuard generated a potential-delay warning."),ev(4,"AI_SUMMARY","2026-09-27T08:05:00Z","AI","A plain-language explanation was generated from the recorded events.")];
export const mockD:Doc[]=[
{id:"d1",file_name:"Acknowledgement.pdf",document_type:"ACKNOWLEDGEMENT",uploaded_at:"2026-09-20T12:10:00Z",extraction_status:"COMPLETED",extracted_data:{complaint_id:{value:"CMP-2026-DEMO-001",confidence:0.96},entity_name:{value:"Demo Brokerage Pvt Ltd",confidence:0.85},submission_date:{value:"2026-09-20",confidence:0.9}}},
{id:"d2",file_name:"Screenshot.png",document_type:"SCREENSHOT",uploaded_at:"2026-09-20T12:15:00Z",extraction_status:"PARTIAL",extracted_data:{complaint_id:{value:"CMP-2026-DEMO-001",confidence:0.71}}}];
export const mockN:NextAction={type:"FOLLOW_UP",title:"Follow-up may be appropriate",description:"A follow-up through the applicable official grievance process may be relevant for this case.",required_documents:["Complaint reference number","Submission date","Acknowledgement","Supporting correspondence"],official_source:null};
export const mockX:Explanation={current_situation:"Your grievance is currently waiting for a response.",timeline_summary:"Your complaint was submitted and an acknowledgement was recorded.",warning_explanation:"No later response has been recorded.",missing_information:["Response correspondence"],next_step_summary:"Review the suggested follow-up action below.",generated_at:"2026-09-27T08:05:00Z"};
export const mockS:Summary={active:1,on_track:0,potentially_delayed:1,resolved:0};
export const mockNotifs:Notif[]=[
{id:"n1",notification_type:"POTENTIAL_DELAY",title:"FlowGuard update",message:"Your grievance CMP-2026-DEMO-001 has remained in its current stage and a follow-up may be appropriate.",read:false,created_at:"2026-09-27T08:01:00Z",grievance_id:"demo-1",channel:"EMAIL_SIMULATED"},
{id:"n2",notification_type:"STATUS_CHANGED",title:"Status updated",message:"CMP-2026-DEMO-001 moved to Awaiting Response.",read:true,created_at:"2026-09-21T08:00:00Z",grievance_id:"demo-1"}];
